#税收说明:  每笔商品的上架和买卖都会被服务器收取指定的税务作为手续费   税收最大为100即为100%
#税务配置and店铺等级  可以无限量的自定义但是推荐不超过9个,不然可能会出现位置错误
#最高上架商品种类 每种物品算一种   上线为:54种  即为9*6  插件后续维护会增减到无限
#激活积分  即销售指定金额后达到的店铺等级   可以利用店铺等级增加商品种类数量
#是否开启点券交易模式   即使用PlayerPoints进行商品的交易

天猫配置:
  创建店铺所需手续费: 1000
  更改店铺图标手续费: 1000
  更改店铺名称手续费: 1000
  店铺名称中不可使用的字符:
    - 国王
    - op
    - 腐竹
税务配置店铺等级:
  青铜店铺:
    税收: 5
    最高上架商品种类: 10
    激活积分: 0
    是否开启点券交易模式: false
  白银店铺:
    税收: 10
    最高上架商品种类: 20
    激活积分: 1000
    是否开启点券交易模式: false
  黄金店铺:
    税收: 15
    最高上架商品种类: 30
    激活积分: 1000
    是否开启点券交易模式: true
help:
  - §e/§a§cTM §dopenTianMao §b打开全部天猫店铺
  - §e/§a§cTM §dopen §e<§5玩家名§e> §b打开指定玩家的店铺
  - §e/§a§cTM §dset ShopName §e<§5玩家名§e> §e<§5店铺名§e> §b设置指定玩家的店铺名称
  - §e/§a§cTM §dset ShopIntegral §e<§5玩家名§e> §e<§5积分§e> §b设置指定玩家的店铺积分
  - §e/§a§cTM §dnewShop §e<§5店铺名称§e> §b创建店铺
  - §e/§a§cTM §dnewShopSale §e<§5价格§e> §b将手上的物品上架自己的商店
  - §e/§a§cTM §ddeleteShop §b删除自己的商店,慎用会删除全部的库存!
  - §e/§a§cTM §ddeleteShopSale §e<§5物品唯一标识§e> §b删除指定的库存!
